server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_oj
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: INFO
    com.mjh: DEBUG
  file:
    name: logs/application.log
